#!/bin/bash

cd $(dirname $0)../


if [ -d build ]; then
    rm -rf build 
fi

if [ -d install ];then
    rm -rf install
fi

mkdir build 
mkdir install 

cd build
cmake -DCMAKE_INSTALL_PREFIX=./install -DBUILD_EXAMPLES=ON  -DENABLE_ICEORYX=On \
 ..
cmake --build . --parallel 10

cmake --build . --target install
